# Header
menu:
  Home: /
  Archives: /archives
  Categories: /categories
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

leancloud_visitors:
  enable: true
  app_id: am8gD5JbPwM9gUEtlYd8n4GQ-gzGzoHsz
  app_key: vdc4LDKp8Wi9X9z0ko3tSYaV
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i> 访问人数
  site_uv_footer: 人次 
  # # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i> 总访问量
  site_pv_footer: 次 
  # custom pv span for one page only
  page_pv: false
  page_pv_header: <i class="fa fa-file-o"></i> 阅读
  page_pv_footer: 次 

valine:
  appid:  am8gD5JbPwM9gUEtlYd8n4GQ-gzGzoHsz
  appkey:  vdc4LDKp8Wi9X9z0ko3tSYaV
  verify: true #验证码
  notify: true #评论回复提醒
  placeholder: 这里留言。。 #评论框占位符